name: Build PDF
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build docker image
      run: |
        docker buildx build lilypond_docker -t lilypond \
          --cache-from type=gha --cache-to type=gha,mode=max
    - name: Run Script in Docker Container
      run: ./build.sh handout
