name: GitHub Actions Demo
on: [push]
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Build Docker Image
      run: docker build lilypond_docker -t lilypond
    - name: Run Script in Docker Container
      run: ./build.sh
